### ISSUE TITLE
两处笔误

### ISSUE THREAD

**Issue by fs20sc** [cycleuser/ThinkPython2-CN#1]
chapter2.md  Line 352
>2.	加入一本书的封面标价是24.95美元

这个"加入"可能是 “假如”吧

chapter3.md  line 77

>数学模块同事也提供了log，用自然底数e取对数的函数。

这个 "同事" 可能是 “同时” 吧.

**Comment by cycleuser** [comment]
确实是这样。谢谢~ 我这就修改一下。
